language: python
python: "3.6"
install:
  - "pip install ."
  - "pip install pytest"
  - "pip install coverage"
  - "pip install coveralls"

before_script:
  - docker pull python:3-alpine
script:
  - python setup.py bdist_wheel
  - docker build --tag "chris060986/pokerstars" .


